Create FactorialNNumber.java
BimalRajGyawali/hacktoberfest-java pull request #105
Opened 2022-10-09 12:25 UTC by Yadnyesh-Dashpute

2022-10-09 15:07 UTC, BimalRajGyawali requested changes

2022-10-09 15:07 UTC, BimalRajGyawali commented on src/main/java/org/example/algorithms/FactorialNNumber.java
> +    public static int Factorial(int n)
Method names should start with lowercase.

2022-10-09 19:44 UTC, Yadnyesh-Dashpute commented
Sir Please Check it I will change the method name in lowercase.

2022-10-10 03:03 UTC, BimalRajGyawali approved these changes

2022-10-10 03:03 UTC, merged